#micro website
wCDGS='coreldraw'
wPTR='painterartist'
wWPO='wordperfect'
wPSP='paintshoppro'
wVSP='videostudiopro'
wASP='aftershotpro'
wPHOTOMIRAGE='Photomirage'

#product
CDGS='coreldraw'
CAD='corel-cad'
CDTS='technical-suite'
CDHS='home-student'
PTR='painter'
PE='painter-essentials'
particleshop='particleshop'
WPOSTD='office-suite'
WPOPRO='professional-edition'
WPOHS='home-student'
PDF='pdf-creator'
PSP='paintshop-pro/standard'
PSU='paintshop-pro/ultimate'
PVB='photo-video-bundle'
VSP='videostudio/pro'
VSU='videostudio/ultimate'
ASP='aftershot/pro'
WinDVD='windvdpro'

#PID for upgrade product
KCDGS='ESDCDGS2019AM'
UCDGS='ESDCDGS2019AMUG'
OCDGS='CDGS2019EFDPECOM'
XCDGS='CDGS2019EFDPECOMUG'
S1CDGS='CDGSSUBPUREPREM1'
S2CDGS='CDGSSUBPUREPREM2'

KCAD='ESDCCAD2019ML'
UCAD='ESDCCAD2019MLUG'
OCAD='CCAD2019MLPCM'
XCAD='CCAD2019MLPCMUG'

KCDTS='ESDCDTS2018ML'
UCDTS='ESDCDTS2018MLUG'
OCDTS='CDTS2018MLDVD'
XCDTS='CDGSDUMMYSKU'
S1CDTS='CDTSSUBSCRIPTION1'
S2CDTS='CDTSSUBSCRIPTION2'

KCDHS='ESDCDHS2018AM'

